src/Entity/Medicament.php
<?php

namespace App\Entity;

use App\Repository\MedicamentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MedicamentRepository::class)
 */
class Medicament extends Produit
{

    /**
     * @ORM\Column(type="datetime")
     */
    private $expire_at;

    /**
     * @ORM\ManyToOne(targetEntity=CategoryMed::class, inversedBy="medicament")
     */
    private $categoryMed;

    public function getExpireAt(): ?\DateTimeInterface
    {
        return $this->expire_at;
    }

    public function setExpireAt(\DateTimeInterface $expire_at): self
    {
        $this->expire_at = $expire_at;

        return $this;
    }

    public function getCategoryMed(): ?CategoryMed
    {
        return $this->categoryMed;
    }

    public function setCategoryMed(?CategoryMed $categoryMed): self
    {
        $this->categoryMed = $categoryMed;

        return $this;
    }
}

src/Form/MedicamentType.php
<?php

namespace App\Form;

use App\Entity\Medicament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MedicamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('codeProd')
            ->add('prixProd')
            ->add('noticeProd')
            ->add('fabriquant')
            ->add('estDisponible')
            ->add('expire_at')
            ->add('rayon')
            ->add('reserve')
            ->add('categoryMed')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Medicament::class,
        ]);
    }
}

src/Controller/MedicamentController.php
<?php

namespace App\Controller;

use App\Entity\Medicament;
use App\Form\Medicament1Type;
use App\Repository\MedicamentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/medicament")
 */
class MedicamentController extends AbstractController
{
    /**
     * @Route("/", name="medicament_index", methods={"GET"})
     */
    /*cette fonction retourne la liste de tous les medicaments*/
    public function index(MedicamentRepository $medicamentRepository): Response
    {
        return $this->render('medicament/index.html.twig', [
            'medicaments' => $medicamentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="medicament_new", methods={"GET","POST"})
     */
    /*cette fonction permet d'ajouter un nouveau medicament*/
    public function new(Request $request): Response
    {
        $medicament = new Medicament();
        $form = $this->createForm(Medicament1Type::class, $medicament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($medicament);
            $entityManager->flush();
            $this->addFlash("success","ajout du nouveau medicament effectué avec succés");

            return $this->redirectToRoute('medicament_index');
        }

        return $this->render('medicament/new.html.twig', [
            'medicament' => $medicament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="medicament_show", methods={"GET"})
     */
    public function show(Medicament $medicament): Response
    {
        return $this->render('medicament/show.html.twig', [
            'medicament' => $medicament,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="medicament_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Medicament $medicament): Response
    {
        $form = $this->createForm(Medicament1Type::class, $medicament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash("success","modification effectué avec succés");

            return $this->redirectToRoute('medicament_index');
        }

        return $this->render('medicament/edit.html.twig', [
            'medicament' => $medicament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="medicament_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Medicament $medicament): Response
    {
        if ($this->isCsrfTokenValid('delete'.$medicament->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($medicament);
            $entityManager->flush();
        }

        return $this->redirectToRoute('medicament_index');
    }
}

templates/medicament/_delete_form.html.twig
<form method="post" action="{{ path('medicament_delete', {'id': medicament.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer ce medicament?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medicament.id) }}"><br>
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/medicament/edit.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Welcome!{% endblock %}</title>

    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('css/sb-admin-2.css') }}">
        <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">




    {% endblock %}
</head>

{% block body %}
    <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laptop-medical"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Gestion des produit
            </div>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-tablets"></i>

                    <span>Medicament</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Medicament</h6>
                        <a class="collapse-item" href="{{ path("medicament_index") }}">Liste des medicaments</a>
                        <a class="collapse-item" href="{{ path('medicament_new') }}">Ajouter un Medicament</a>
                        <a class="collapse-item" href="{{ path('category_med_index') }}">Liste des categories</a>
                        <a class="collapse-item" href="{{ path('category_med_new') }}">Ajouter un categorie</a>

                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities2"
                   aria-expanded="true" aria-controls="collapseUtilities2">
                    <i class="fas fa-pump-medical"></i>

                    <span>Parapharmacie</span>
                </a>
                <div id="collapseUtilities2" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Parapharmacie</h6>
                        <a class="collapse-item" href="{{ path('parapharmacie_index') }}">Liste des produits</a>
                        <a class="collapse-item" href="{{ path('parapharmacie_new') }}">Ajouter un produit </a>

                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities3"
                   aria-expanded="true" aria-controls="collapseUtilities3">
                    <i class="fas fa-stethoscope fa-lg"></i>
                    <span>Accessoire Medical</span>
                </a>
                <div id="collapseUtilities3" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Accessoire Medical</h6>
                        <a class="collapse-item" href="{{ path('accessoir_med_index') }}">Liste des accessoires </a>
                        <a class="collapse-item" href="{{ path('accessoir_med_new') }}">Ajouter un accesoire</a>

                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Partenaires
            </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities4"
                   aria-expanded="true" aria-controls="collapseUtilities4">
                    <i class="fas fa-truck"></i>

                    <span>Fournisseurs</span>
                </a>
                <div id="collapseUtilities4" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Fournisseurs</h6>
                        <a class="collapse-item" href="{{ path('fournisseur_index') }}">Liste des fournisseurs</a>
                        <a class="collapse-item" href="{{ path('fournisseur_new') }}">Ajouter un fournisseur</a>
                        <a class="collapse-item" href="{{ path('fournir_index') }}">Liste des livraisons</a>
                        <a class="collapse-item" href="{{ path('fournir_new') }}">Ajouter une livraison</a>
                    </div>

                </div>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <div class="sidebar-heading">
                Emplacements
            </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities5"
                   aria-expanded="true" aria-controls="collapseUtilities5">
                    <i class="fas fa-align-justify"></i>

                    <span>Rayons</span>
                </a>
                <div id="collapseUtilities5" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Rayons</h6>
                        <a class="collapse-item" href="{{ path('rayon_index') }}">Les Rayons</a>
                        <a class="collapse-item" href="{{ path('rayon_new') }}">Ajouter un nouveau rayon</a>
                    </div>

                </div>
            </li>
            <hr class="sidebar-divider">
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{{ path('admin',{'id':4}) }}">
                    <i class="fas fa-user-circle"></i>
                    <span>Mon compte</span></a>
            </li>
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{{ path('logout') }}">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>deconnexion</span></a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">


            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                </nav>                        <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4  font-weight-bold text-primary">Modification de  Medicament</h1>
                    <div class="page-top">

                        {{ form_start(form) }}
                        {{ form_widget(form)}}
                        <input type="submit" class="btn btn-success" value="Enregistrer les modifications">
                        {{ form_end(form) }}

                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>



    </body>

{% endblock %}
</html>

templates/medicament/show.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Welcome!{% endblock %}</title>

    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('css/sb-admin-2.css') }}">
        <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">




    {% endblock %}
</head>

{% block body %}
    <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laptop-medical"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Gestion des produit
            </div>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-tablets"></i>

                    <span>Medicament</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Medicament</h6>
                        <a class="collapse-item" href="{{ path('medicament_index') }}">Liste des medicaments</a>
                        <a class="collapse-item" href="{{ path('medicament_new') }}">Ajouter un Medicament</a>
                        <a class="collapse-item" href="{{ path('category_med_index') }}">Liste des categories</a>
                        <a class="collapse-item" href="{{ path('category_med_new') }}">Ajouter un categorie</a>

                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities2"
                   aria-expanded="true" aria-controls="collapseUtilities2">
                    <i class="fas fa-pump-medical"></i>

                    <span>Parapharmacie</span>
                </a>
                <div id="collapseUtilities2" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Parapharmacie</h6>
                        <a class="collapse-item" href="{{ path('parapharmacie_index') }}">Liste des produits</a>
                        <a class="collapse-item" href="{{ path('parapharmacie_new') }}">Ajouter un produit </a>

                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities3"
                   aria-expanded="true" aria-controls="collapseUtilities3">
                    <i class="fas fa-stethoscope fa-lg"></i>
                    <span>Accessoire Medical</span>
                </a>
                <div id="collapseUtilities3" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Accessoire Medical</h6>
                        <a class="collapse-item" href="{{ path('accessoir_med_index') }}">Liste des accessoires </a>
                        <a class="collapse-item" href="{{ path('accessoir_med_new') }}">Ajouter un accesoire</a>

                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Partenaires
            </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities4"
                   aria-expanded="true" aria-controls="collapseUtilities4">
                    <i class="fas fa-truck"></i>

                    <span>Fournisseurs</span>
                </a>
                <div id="collapseUtilities4" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Fournisseurs</h6>
                        <a class="collapse-item" href="{{ path('fournisseur_index') }}">Liste des fournisseurs</a>
                        <a class="collapse-item" href="{{ path('fournisseur_new') }}">Ajouter un fournisseur</a>
                        <a class="collapse-item" href="{{ path('fournir_index') }}">Liste des livraisons</a>
                        <a class="collapse-item" href="{{ path('fournir_new') }}">Ajouter une livraison</a>
                    </div>

                </div>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <div class="sidebar-heading">
                Emplacements
            </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities5"
                   aria-expanded="true" aria-controls="collapseUtilities5">
                    <i class="fas fa-align-justify"></i>

                    <span>Rayons</span>
                </a>
                <div id="collapseUtilities5" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Rayons</h6>
                        <a class="collapse-item" href="{{ path('rayon_index') }}">Les Rayons</a>
                        <a class="collapse-item" href="{{ path('rayon_new') }}">Ajouter un nouveau rayon</a>
                    </div>

                </div>
            </li>
            <hr class="sidebar-divider">
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{{ path('admin',{'id':4}) }}">
                    <i class="fas fa-user-circle"></i>
                    <span>Mon compte</span></a>
            </li>
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{{ path('logout') }}">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>deconnexion</span></a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">


            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                </nav>                        <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4  font-weight-bold text-primary">Medicament</h1>
                    <div class="page-top">

                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Nom</th>
                                <td>{{ medicament.nom }}</td>
                            </tr>
                            <tr>
                                <th>CodeProd</th>
                                <td>{{ medicament.codeProd }}</td>
                            </tr>
                            <tr>
                                <th>PrixProd</th>
                                <td>{{ medicament.prixProd }}</td>
                            </tr>
                            <tr>
                                <th>NoticeProd</th>
                                <td>{{ medicament.noticeProd }}</td>
                            </tr>
                            <tr>
                                <th>Fabriquant</th>
                                <td>{{ medicament.fabriquant }}</td>
                            </tr>
                            <tr>
                                <th>EstDisponible</th>
                                <td>{{ medicament.estDisponible ? 'Yes' : 'No' }}</td>
                            </tr>
                            <tr>
                                <th>Stock</th>
                                <td>{{ medicament.stock }}</td>
                            </tr>
                            <tr>
                                <th>Expire_at</th>
                                <td>{{ medicament.expireAt ? medicament.expireAt|date('Y-m-d H:i:s') : '' }}</td>
                            </tr>
                            </tbody>
                        </table>


                        <a href="{{ path('medicament_edit', {'id': medicament.id}) }}"><button class="btn btn-warning">edit</button></a>

                        {{ include('medicament/_delete_form.html.twig') }}
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>



    </body>

{% endblock %}
</html>